### ISSUE TITLE
payment issue

### ISSUE THREAD

**Issue by beatific-angel** [eMerchantPay/woocommerce-emp-plugin#2]
I purchased this plugin in here for davivienda
davivienda.php is in here.
so I installed this plugin and check this plugin
I can see another some pays
but i can not show davivienda
what is reason?
Can I use davivienda as a payment method here?
---URGENT---
![0607](https://user-images.githubusercontent.com/64799935/83964512-3f6f6280-a8b6-11ea-849a-aec34a6eadc0.png)
![060701](https://user-images.githubusercontent.com/64799935/83964585-b9075080-a8b6-11ea-9d00-dac3b8ef6e2c.png)

**Comment by dyd** [comment]
Hello @Mihail-823,

For such a request, I have to ask you to contact our Tech Support Team. 
Here is contact - tech-support@emerchantpay.com.
For better and faster reactions from our team, please include in your request:
    * you're interested in WooCommerce shopping cart
    * specify your merchant name in a Staging environment
    * specify that you're interested in <strong>Davivienda</strong> Alternative Payment Method

Best Regards
